apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "-25"
  name: ldap-ca
  namespace: openshift-config
data:
  ca.crt: |
  Your-certificate-to-access-LDAP
