apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "-25"
  name: ldap-bind-password
  namespace: openshift-config
data:
  bindPassword: Your-LDAP-Password
