apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hub-only.yaml
  - ocp-post-deployment-clusters.yaml
  - ocp-release-4.12-clusters.yaml
  - ocp-release-4.14-clusters.yaml
