---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ocp-post-deployment-clusters
  namespace: open-cluster-management
spec:
  clusterConditions:
  - status: 'True'
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - sample-cluster
#      - local-cluster

