---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: release-4.12-clusters
  namespace: open-cluster-management
spec:
  clusterConditions:
  - status: 'True'
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - sample-ocp412-cluster

