---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: release-4.8-clusters
  namespace: channel-postinstall-policies
spec:
  clusterConditions:
  - status: 'True'
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
 #   - key: vendor
 #     operator: In
 #     values:
 #     - OpenShift
    - key: name
      operator: In
      values:

